"use client";

import { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Github, Star, Search, Zap, ArrowUpRight } from "lucide-react";

interface Project {
  id: string;
  name: string;
  repo_name: string;
  description: string;
  github_url: string;
  category: string;
  tech_stack: string[];
  date: string;
  built_by_nexus: boolean;
  wow_factor: number;
  summary: string;
}

interface ProjectsData {
  last_updated: string;
  total_projects: number;
  projects: Project[];
}

/* Category accent colours */
const categoryColors: Record<string, string> = {
  "Streaming":         "#8b5cf6",
  "Batch ETL":         "#f59e0b",
  "Lakehouse":         "#34d399",
  "Observability":     "#60a5fa",
  "ML Platform":       "#f472b6",
  "Data Quality":      "#fb923c",
};
const defaultAccent = "#8b5cf6";

function accentFor(cat: string) {
  return categoryColors[cat] ?? defaultAccent;
}

/* Wow-factor colour */
function wowColor(n: number) {
  if (n >= 9) return "#f59e0b";
  if (n >= 7) return "#8b5cf6";
  return "#64748b";
}

export default function ProjectsPage() {
  const [data,     setData]     = useState<ProjectsData | null>(null);
  const [search,   setSearch]   = useState("");
  const [category, setCategory] = useState("All");
  const [loading,  setLoading]  = useState(true);

  useEffect(() => {
    fetch("/projects_data.json")
      .then((r) => r.json())
      .then((d) => { setData(d); setLoading(false); })
      .catch(() => setLoading(false));
  }, []);

  const categories = data
    ? ["All", ...Array.from(new Set(data.projects.map((p) => p.category)))]
    : ["All"];

  const filtered = data?.projects.filter((p) => {
    const matchCat   = category === "All" || p.category === category;
    const matchSearch =
      !search ||
      p.name.toLowerCase().includes(search.toLowerCase()) ||
      p.description.toLowerCase().includes(search.toLowerCase()) ||
      p.tech_stack.some((t) => t.toLowerCase().includes(search.toLowerCase()));
    return matchCat && matchSearch;
  }) ?? [];

  return (
    <main className="min-h-screen bg-[#080810] pt-28 pb-24">
      <div className="max-w-7xl mx-auto px-6">

        {/* ── Page header ───────────────────────────────── */}
        <div className="mb-16">
          <span
            className="text-violet-400 text-xs tracking-[0.25em] uppercase block mb-6"
            style={{ fontFamily: "var(--font-mono)" }}
          >
            Portfolio
          </span>
          <div className="flex flex-col md:flex-row md:items-end justify-between gap-6">
            <h1
              className="text-white leading-none"
              style={{
                fontSize: "clamp(2.5rem, 7vw, 5.5rem)",
                fontFamily: "var(--font-display)",
                fontWeight: 800,
                letterSpacing: "-0.04em",
              }}
            >
              Data Engineering<br />
              <span className="gradient-text">Projects</span>
            </h1>
            <div className="md:text-right shrink-0">
              {data && (
                <p
                  className="text-slate-600 text-sm"
                  style={{ fontFamily: "var(--font-mono)" }}
                >
                  {data.total_projects} projects · synced {data.last_updated.slice(0, 10)}
                </p>
              )}
              <p className="text-slate-600 text-sm mt-1">
                Auto-generated by{" "}
                <span className="text-violet-400 font-semibold" style={{ fontFamily: "var(--font-mono)" }}>
                  NEXUS AI Agent
                </span>
              </p>
            </div>
          </div>
        </div>

        {/* ── Filters ───────────────────────────────────── */}
        <div className="flex flex-col sm:flex-row gap-4 mb-10">
          {/* Search */}
          <div className="relative flex-1 max-w-sm">
            <Search
              size={14}
              className="absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-600 pointer-events-none"
            />
            <input
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              placeholder="Search projects or tech…"
              className="w-full pl-10 pr-4 py-2.5 bg-white/[0.03] border border-white/[0.08] rounded-xl text-slate-300 placeholder:text-slate-700 text-sm outline-none focus:border-violet-500/40 transition-colors"
              style={{ fontFamily: "var(--font-mono)" }}
            />
          </div>

          {/* Category pills */}
          <div className="flex flex-wrap gap-2">
            {categories.map((cat) => (
              <button
                key={cat}
                onClick={() => setCategory(cat)}
                className={`px-4 py-2 rounded-xl text-xs font-medium transition-all duration-200 ${
                  category === cat
                    ? "bg-violet-600 text-white shadow-lg shadow-violet-500/20"
                    : "bg-white/[0.03] border border-white/[0.07] text-slate-500 hover:text-white hover:border-white/20"
                }`}
                style={{ fontFamily: "var(--font-mono)" }}
              >
                {cat}
              </button>
            ))}
          </div>
        </div>

        {/* ── Grid / State ──────────────────────────────── */}
        {loading ? (
          /* Skeleton */
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-5">
            {Array.from({ length: 6 }).map((_, i) => (
              <div
                key={i}
                className="rounded-2xl border border-white/[0.06] h-64 overflow-hidden relative"
              >
                <div className="animate-shimmer absolute inset-0" />
              </div>
            ))}
          </div>
        ) : filtered.length === 0 ? (
          <div className="flex flex-col items-center justify-center py-32 text-center">
            <Zap size={36} className="text-slate-700 mb-4" />
            <p className="text-slate-600 text-lg">
              {!data || data.total_projects === 0
                ? "NEXUS is generating the first project now…"
                : "No projects match your search."}
            </p>
          </div>
        ) : (
          <AnimatePresence mode="popLayout">
            <motion.div layout className="grid md:grid-cols-2 lg:grid-cols-3 gap-5">
              {filtered.map((project, i) => {
                const accent = accentFor(project.category);
                return (
                  <motion.article
                    key={project.id}
                    layout
                    initial={{ opacity: 0, y: 24 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, scale: 0.97 }}
                    transition={{ delay: i * 0.04, ease: [0.16, 1, 0.3, 1] }}
                    className="group relative flex flex-col rounded-2xl border border-white/[0.07] bg-white/[0.02] p-6 overflow-hidden hover:-translate-y-1 hover:border-white/[0.14] transition-all duration-300"
                  >
                    {/* Accent glow on hover */}
                    <div
                      className="absolute inset-0 opacity-0 group-hover:opacity-100 transition-opacity duration-500 pointer-events-none rounded-2xl"
                      style={{
                        background: `radial-gradient(circle at top right, ${accent}0f 0%, transparent 60%)`,
                      }}
                    />

                    {/* Top row */}
                    <div className="flex items-start justify-between mb-4">
                      <div className="flex items-center gap-2 flex-wrap">
                        {project.built_by_nexus && (
                          <span
                            className="text-[10px] px-2 py-0.5 rounded-full border"
                            style={{
                              borderColor: `${accent}35`,
                              background: `${accent}10`,
                              color: accent,
                              fontFamily: "var(--font-mono)",
                            }}
                          >
                            NEXUS
                          </span>
                        )}
                        <span
                          className="text-slate-600 text-[10px]"
                          style={{ fontFamily: "var(--font-mono)" }}
                        >
                          {project.date}
                        </span>
                      </div>

                      {/* Wow factor */}
                      <div
                        className="flex items-center gap-1 shrink-0"
                        style={{ color: wowColor(project.wow_factor) }}
                      >
                        <Star size={11} fill="currentColor" />
                        <span
                          className="text-[11px] font-semibold"
                          style={{ fontFamily: "var(--font-mono)" }}
                        >
                          {project.wow_factor}
                        </span>
                      </div>
                    </div>

                    {/* Title */}
                    <h3
                      className="text-white text-base mb-3 leading-tight group-hover:text-violet-200 transition-colors"
                      style={{ fontFamily: "var(--font-display)", fontWeight: 700 }}
                    >
                      {project.name}
                    </h3>

                    {/* Description */}
                    <p className="text-slate-600 text-sm leading-relaxed line-clamp-3 flex-1 mb-5">
                      {project.description}
                    </p>

                    {/* Tech tags */}
                    <div className="flex flex-wrap gap-1.5 mb-5">
                      {project.tech_stack.slice(0, 4).map((tech) => (
                        <span key={tech} className="tag">{tech}</span>
                      ))}
                      {project.tech_stack.length > 4 && (
                        <span
                          className="text-slate-700 text-[10px] px-2 py-0.5"
                          style={{ fontFamily: "var(--font-mono)" }}
                        >
                          +{project.tech_stack.length - 4}
                        </span>
                      )}
                    </div>

                    {/* Bottom row */}
                    <div className="flex items-center justify-between pt-4 border-t border-white/[0.05]">
                      <span
                        className="text-[10px] px-2.5 py-1 rounded-lg border border-white/[0.07] text-slate-600"
                        style={{ fontFamily: "var(--font-mono)" }}
                      >
                        {project.category}
                      </span>
                      <a
                        href={project.github_url}
                        target="_blank"
                        rel="noreferrer"
                        className="flex items-center gap-1.5 text-slate-600 hover:text-violet-400 transition-colors text-xs"
                        style={{ fontFamily: "var(--font-mono)" }}
                      >
                        <Github size={13} /> View Code
                        <ArrowUpRight size={11} />
                      </a>
                    </div>
                  </motion.article>
                );
              })}
            </motion.div>
          </AnimatePresence>
        )}

        {/* Footer note */}
        {!loading && data && (
          <div
            className="text-center mt-12 text-slate-700 text-xs"
            style={{ fontFamily: "var(--font-mono)" }}
          >
            Showing {filtered.length} of {data.total_projects} projects ·{" "}
            <a
              href="https://github.com/naveenkanaparthi-git"
              target="_blank"
              rel="noreferrer"
              className="text-violet-600 hover:text-violet-400 transition-colors"
            >
              github.com/naveenkanaparthi-git
            </a>
          </div>
        )}
      </div>
    </main>
  );
}
